{
 "title": "Instances overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Serveur",
    "query": "VPN : xxx:9100, k3s-Master : xxx:9100, k3s-Worker : xxx:9100"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU (7d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((100 - (avg without (cpu) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100))[7d:5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RAM (7d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((100 * (1 - ((node_memory_MemFree_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\"})))[7d:5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Disk (7d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", instance=~\"$instance\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", instance=~\"$instance\"}))[7d:5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg without (cpu) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disque (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", instance=~\"$instance\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "More",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk I/O (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[5m]) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}