apiVersion: v1
kind: Endpoints
metadata:
  name: vpn-node-exporter
  namespace: monitoring
  labels:
    app: vpn-node-exporter
subsets:
  - addresses:
      - ip: xxx
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-node-exporter
  namespace: monitoring
  labels:
    app: vpn-node-exporter
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpn-node-exporter
  namespace: monitoring
  labels:
    release: supervision
spec:
  selector:
    matchLabels:
      app: vpn-node-exporter
  endpoints:
    - port: metrics